export const FORUM_POSTS = [
    {
        id: 0,
        book: "Great Expectations",
        topic: "Violence and Terror in the writings of Dickens",
        parent: 0,
        private: false,
        name: "Ben Eastvold",
        date: "3:01 PM, Feb 12",
        description: "Charles Dickens explores the dark underbelly of Victorian society. In a culture that prided itself on formalities and decorum, the poor and vulnerable were often neglected. What is your own experience in recognizing (or not recognizing) the vulnerable in your own city or culture?",
    },
    {
        id: 1,
        book: "Great Expectations",
        topic: "Violence and Terror in the writings of Dickens",
        parent: 0,
        private: true,
        name: "Jill MacIntosh",
        date: "10:42 AM, Feb 13",
        description: "Wow. Deep question. I have to admit that my comfortable life often keeps me distant from the suffering of others. I don't like that.",
    },
    {
        id: 2,
        book: "Great Expectations",
        topic: "Violence and Terror in the writings of Dickens",
        parent: 0,
        private: false,
        name: "Janet Jackson",
        date: "7:15 PM, Yesterday",
        description: "As my brother used to say, 'Heal the world; make it a better place for you and for me and for the entire human race.'"
    },
    {
        id: 3,
        book: "Great Expectations",
        topic: "Chapter 1 Questions",
        parent: 3,
        private: false,
        name: "A Really Importnat Teacher",
        date: "3:01 PM, Today",
        description: "As you finish your first week of reading, here are some questions to discuss about the first chapter. What do you find surprising about the narrative point-of-view Dickens has adopted? What literary techniques does Dickens use to convery the mood right from the opening?",
    },
    {
        id: 4,
        book: "Great Expectations",
        topic: "Chapter 1 Questions",
        parent: 3,
        private: false,
        name: "Walt Whitman",
        date: "5:12 PM, Today",
        description: "Dickens begins the story from Pip's perspective, a poor orphan child. By using him as the narrating character, it builds identification and compassion with the reader. Yet even from the opening line, we see that Pip has taken some sort of control of his life; he is not a victim. Though his name is actually Phillip, but, 'I called myself Pip, and came to be called Pip.'",
    },
    {
        id: 5,
        book: "Great Expectations",
        topic: "Violence and Terror in the writings of Dickens",
        parent: 1,
        private: false,
        name: "Ben Eastvold",
        date: "7:15 PM, Today",
        description: "Thank you for sharing, Jill. Yes, that is my hope for this course - that we would allow Dickens to open our eyes to the plight of others here and now."
    },
];